// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration.
///
/// This file is automatically generated by FlutterFire CLI.
/// Do NOT edit manually.
///
/// Run:
/// flutterfire configure
///
/// whenever you change Firebase project settings.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.\n'
          'Run "flutterfire configure".',
        );

      default:
        throw UnsupportedError('This platform is not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUg3ePd9vN2l9L1HWFhUOEl8Fm3apczqE',
    appId: '1:327434489432:android:50237f2f2055624103842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    storageBucket: 'tib-grooming.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4-ffEyeuB7zKbv2j-H_HHprFIigKu5Y',
    appId: '1:327434489432:web:9b028d40a9ac284903842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    authDomain: 'tib-grooming.firebaseapp.com',
    storageBucket: 'tib-grooming.firebasestorage.app',
    measurementId: 'G-W9P08PLRJD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc54TJlOKEgcmyUZosmb2VMUFwdoIWf5U',
    appId: '1:327434489432:ios:746f279cfc120a6103842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    storageBucket: 'tib-grooming.firebasestorage.app',
    iosBundleId: 'com.example.tibGroomingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc54TJlOKEgcmyUZosmb2VMUFwdoIWf5U',
    appId: '1:327434489432:ios:746f279cfc120a6103842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    storageBucket: 'tib-grooming.firebasestorage.app',
    iosBundleId: 'com.example.tibGroomingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD4-ffEyeuB7zKbv2j-H_HHprFIigKu5Y',
    appId: '1:327434489432:web:9b028d40a9ac284903842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    authDomain: 'tib-grooming.firebaseapp.com',
    storageBucket: 'tib-grooming.firebasestorage.app',
    measurementId: 'G-W9P08PLRJD',
  );
}
