// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration.
///
/// This file is automatically generated by FlutterFire CLI.
/// Do NOT edit manually.
///
/// Run:
/// flutterfire configure
///
/// whenever you change Firebase project settings.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for Web.\n'
        'Run "flutterfire configure" to configure your project.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS.\n'
          'Run "flutterfire configure".',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.\n'
          'Run "flutterfire configure".',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.\n'
          'Run "flutterfire configure".',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.\n'
          'Run "flutterfire configure".',
        );

      default:
        throw UnsupportedError('This platform is not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUg3ePd9vN2l9L1HWFhUOEl8Fm3apczqE',
    appId: '1:327434489432:android:50237f2f2055624103842d',
    messagingSenderId: '327434489432',
    projectId: 'tib-grooming',
    storageBucket: 'tib-grooming.firebasestorage.app',
  );
}
